#!/usr/bin/env php
<?php

define('HOST'   , "localhost");
define('PORT'   , "1919");
define('APPNAME', "mdb");
define('VERSION', "0.0.1");
define('DIR', getcwd());
define('APP_DIR', __DIR__);

if (empty($argv)) {
	mdb_print_usage();
}

$CMD = isset($argv[1]) ? $argv[1] : '';

system_check();

$cmdTree = array(
	'version' => function(){println(APPNAME, VERSION);},
	'help' => 'mdb_print_usage',
	'server' =>  'server_web',
	'gen' =>  function() {DIR . '/public/generate.php';},
);

if (isset($cmdTree[$CMD])) {
	if (is_callable($cmdTree[$CMD])) {
		echo $cmdTree[$CMD]();
	}
} else {
	server_web();
}


function server_web() {
	$HOST = HOST;
	$PORT = PORT;
	$dir = getcwd();
	println("Listening on http://$HOST:$PORT");
	println("Document root is $dir. ^C to exit.");
	// println("php -S $HOST:$PORT public/index.php"); exit;
	$appDir = APP_DIR;
	$a = popen("php -S $HOST:$PORT $appDir/public/index.php", 'r');
	while($b = fgets($a, 2048)) {
		echo $b;
	}
	pclose($a);
	exit;
}

function mdb_print_usage($code=0) {
	$APPNAME = APPNAME;
	echo <<<MDBDOC
$APPNAME usage:
	$APPNAME version : show versions
	$APPNAME server  : start start local development server for testing (DO NOT use for production)

MDBDOC;
	exit($code);
}

function system_check(){
	if (!is_file(APP_DIR . '/config.json')) {
		if (is_file(APP_DIR . '/config.json.sample')) {
			println('Init file:', 'config.json');
			copy(APP_DIR . '/config.json.sample', APP_DIR . '/config.json');
		}
		else {
			$APPNAME = APPNAME;
			println("You are running $APPNAME from outside $APPNAME project.");
			exit(1);
		}
	}
}

function println() {
	echo implode(" ", func_get_args()), PHP_EOL;
}

function execute($cmd) {
    $proc = proc_open($cmd, [['pipe','r'],['pipe','w'],['pipe','w']], $pipes);
    while(($line = fgets($pipes[1])) !== false) {
        fwrite(STDOUT,$line);
    }
    while(($line = fgets($pipes[2])) !== false) {
        fwrite(STDERR,$line);
    }
    fclose($pipes[0]);
    fclose($pipes[1]);
    fclose($pipes[2]);
    return proc_close($proc);
}
